### ISSUE TITLE
Please replace 'Pacman' with default Magento spinner.

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#10]
Now we have Pacman and caption below. I do not know if there should be a caption. Please contact  @vkublytskyi.

![image002](https://user-images.githubusercontent.com/11827230/37473251-a8363144-2876-11e8-9dde-af7f98f67823.png)

**Comment by piotrekkaminski** [comment]
The caption should say "Redirecting to Magento Admin Panel".  No access granted ok, no paman

**Comment by phoenix128** [comment]
Fixed in 904a78ffacf1729b528ba4ecc543a935afcaadde
