### ISSUE TITLE
The push message should be configurable

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#11]
When sending push message, the message says “Login request for Default Store View” should be either Login request for Magento Admin Panel” and it should be configurable or “Login Request for [STORE NAME] Admin Panel” non configurable (see screenshot below).

![unnamed](https://user-images.githubusercontent.com/11827230/37474031-1736a99c-2878-11e8-8526-c61b456b5911.jpg)

Is it possible to configure?

**Comment by phoenix128** [comment]
Fixed in https://github.com/magespecialist/magespecialist_TwoFactorAuth/commit/904a78ffacf1729b528ba4ecc543a935afcaadde

**Comment by TomashKhamlai** [comment]
@piotrekkaminski, I expected that this line of code will print out the name of the store, but actually, it doesn't.
storeManager->getStore()->getName()
Instead of the Store name we've got the name of the Store View.

Let write some words about configuring this message on Magento Open Source:
1. Create an admin with all privileges.
2. Create one more Website with Store and Store View
3. Edit the Website to make it the default (tick the checkbox)
4. Save the changes and perform reindexing and cache flushing

Actual result:
![screenshot_20180305_000000000](https://user-images.githubusercontent.com/11827230/37704171-d8406b14-2d00-11e8-8290-b983cf96ee38.png)

![screenshot_20180321_115931](https://user-images.githubusercontent.com/11827230/37703875-c8b81530-2cff-11e8-8457-f397bf233a0f.png)

I tried to figure out why we need to specify the store or the store view and developers told me that there is a possibility to give permissions to separate websites on Magento Commerce edition. Is the goal reached? Can I close it?

**Comment by piotrekkaminski** [comment]
i expected it to use Store Name from Configuration. However this setting has Store View scope.
![image](https://user-images.githubusercontent.com/1714545/37832292-28b9b0de-2e76-11e8-8222-f1acc378b480.png)

so it still looks weird and should be changed to just "Login request to your Magento Admin" (static content)

**Comment by phoenix128** [comment]
Do you prefer to define a text from backend configuration?
We could preconfigure it with "Login request to your Magento Admin" and allow the user to change it.
IMHO allowing to change it is a good idea, because if you are administrating multiple installations, a different message, could be fine.

**Comment by piotrekkaminski** [comment]
yes - that would be great if it is config option, with default to "Login request to your Magento Admin"

**Comment by phoenix128** [comment]
Added in https://github.com/magespecialist/magespecialist_TwoFactorAuth/commit/c44362fc04e874808c209fa8e80ee834b260928e
