### ISSUE TITLE
Why DI xml file from admin area uses wrong XSD?

### ISSUE THREAD

**Issue by mariuscris** [magento/magespecialist_TwoFactorAuth#16]
Hello,

We discovered a possible issue within next XML file: https://github.com/magento/magespecialist_TwoFactorAuth/blob/2.3-develop/etc/adminhtml/di.xml 

Usually in this file we expected that XSD file is set to urn:magento:framework:ObjectManager/etc/config.xsd but here is set to urn:magento:framework:Event/etc/events.xsd. Because of this we had some issue in admin and we fix it using the right XSD. 

It will be nice to know if this is intentional or this is a issue?

Thank you very much for your time.

**Comment by phoenix128** [comment]
No, it is our mistake. Thank you for pointing it out.
