### ISSUE TITLE
::providers, ::users, ::users_config and ::trusted_devices resources should not be listed in User Roles if it has no effect  

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#2]
It is known that any User with the custom resource access cannot manage System > Extensions > Integration but it also not listed in the Role Resources so I think it's OK. But it is possible to grant Two Factor Auth for some User and it will be useless. So it should not be listed or it should have an effect on the Users Configuration. If users with custom resource access will have the access to Two Factor Auth configuration then I suggest placing Two Factor Auth node under Stores - Settings - Configuration node like this was done in Magento UI.

### Preconditions

1. TwoFactorAuth module is active.
2. Google Authenticator is enabled but not forced.

### Steps to reproduce

1. Navigate to System > Permissions > User Roles
2. Press 'Add New Role' button to create a new role.
3. Fill all the required fields in the Role Info tab
4. Set 'Resource Access to' to 'Custom' in the Role Resources tab and mark permissions to:
- Two Factor Auth (and all sub-nodes)
- Stores - Settings - Configuration - Catalog Section - Catalog Search (tick only the last node)
- System - Other Settings - Notifications - Show List (tick only the last node)
5. Create the new user and assign this role to it. 
6. Log out and log in as the User that was created in the previous step.
7. Enable Google Authenticator for current user
### Expected result

1. Any user with granted rights for managing to **::providers**, **::users**, **::users_config** and **::trusted_devices** resources is able to use them.

### Actual result

1. It is impossible to enable Google Authenticator
![at](https://user-images.githubusercontent.com/11827230/35224835-08d8f9ac-ff8f-11e7-9f66-e234f55e0f57.png)

**Comment by phoenix128** [comment]
I'm not sure I got the point.
As far as I can understand, it is correct this user cannot handle 2FA configuration.

**Comment by TomashKhamlai** [comment]
Considering that I have two 2 admins with 2 different user roles: one role gives full access and another role gives only access to the resources that are enabled on the screenshot below, I believe that the second admin will be able to manage Providers Mangement, Users, Users Configuration, Trusted Devices. False according to the second screenshot below.

![step1](https://user-images.githubusercontent.com/11827230/36315367-28ecdbc2-1340-11e8-8712-44acc5c8f1d6.png)

![result](https://user-images.githubusercontent.com/11827230/36315383-32e21ad4-1340-11e8-9dfd-7326a61b3610.png)

I mean that I cannot go to System > Permissions > All Users and manage the way I want to authenticate.

**Comment by TomashKhamlai** [comment]
> It is known that any User with the custom resource access cannot manage System > Extensions > Integration but it also not listed in the Role Resources so I think it's OK

The issue was fixed, so not a good example.

**Comment by phoenix128** [comment]
Ok, I got the point now. I misplaced the ACL root.

**Comment by phoenix128** [comment]
I also think I should give just one option: 2FA yes/no, otherwise it will be a nonsense.

**Comment by phoenix128** [comment]
This should be fixed. You will probably need to reconfigure roles.

**Comment by vkublytskyi** [comment]
Works as expected for me as well

**Comment by TomashKhamlai** [comment]
Re-tested. It works as expected except one little detail that will be covered in another issue. Another problem is identical to the problem we had in core functionality so I hope that links to the issue and PR will give you enough information for finding and fixing. Closing this issue.
