### ISSUE TITLE
Please add composer package name to repo name or description

### ISSUE THREAD

**Issue by tmotyl** [magento/magespecialist_TwoFactorAuth#27]
Right now it's not possible to find this repo when searching with "msp/twofactorauth" on Magento Github repository list https://github.com/magento, or main github search.

Adding composer package name to repo title or descriptio will fix that.

**Comment by sdzhepa** [comment]
Hello @tmotyl 

It seems this issue is not actual anymore.
All future development for 2.4.x will be in this project https://github.com/magento/security-package/ 

Please see https://github.com/magento/security-package/pull/14 for more details
