### ISSUE TITLE
The command php bin/magento msp:security:tfa:reset do not have the success or error message and accepting anything as a param

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#3]
The command
`php bin/magento msp:security:tfa:reset`
requires two additional parameters  `<user>` and `<provider>`. The only way to get the list of providers is to look into `app/code/MSP/TwoFactorAuth/Command/TfaReset.php` and find there `google`, `authy` and `u2fkey`.
(Where is the duo? How to check what is available?)

The command accepts anything as the last param and this makes the guessing of the provider's name even harder. There is no success message if the provider was guessed.
![at](https://user-images.githubusercontent.com/11827230/35231820-7659212e-ffa2-11e7-96d5-db722517ecba.png)

**Comment by phoenix128** [comment]
Fixed by https://github.com/magespecialist/magespecialist_TwoFactorAuth/commit/fc443b6b459b5c1a4163f615e37076a984e78b4b.

Added a new command line tool to get a list of available providers.
