### ISSUE TITLE
Table should be specified in MySQL query in "...WHERE (`user_id` = '1')..."

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#4]
### Preconditions
1. "Enable Two Factor Auth" is set to "Yes" and "Force providers" is set to "Google Authenticator" in Stores > Settings > Configuration > Security Suite > 2FA > General.
2. "Enable this provider" is set "Yes" and "Enable 'trust this device' option" is set to  "Yes" in Stores > Settings > Configuration > Security Suite > 2FA > Google Authenticator.

### Steps to reproduce
Login to Admin and tick "Remember this device" before submitting GAuth form
Navigate to System -> Permissions -> All Users
Edit current Admin. Revoke trusted devices in 2FA tab

### Expected result
:white_check_mark: Under USER INFORMATION section in 2FA tab, there should be option to forgot device

### Actual result
:x: Backend error visible on the front-end
```mysql
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `detail_role`.`role_name` FROM `admin_user` AS `main_table` LEFT JOIN `authorization_role` AS `user_role` ON main_table.user_id = user_role.user_id AND user_role.parent_id != 0 LEFT JOIN `authorization_role` AS `detail_role` ON user_role.parent_id = detail_role.role_id WHERE (`user_id` = '1')
```
![Screenshot](https://user-images.githubusercontent.com/11827230/35274939-b7940d3a-0046-11e8-812a-4f201d3630d5.png)

Let me guess the correct query is:
```mysql
SELECT `main_table`.*, `detail_role`.`role_name` FROM `admin_user` AS `main_table` LEFT JOIN `authorization_role` AS `user_role` ON main_table.user_id = user_role.user_id AND user_role.parent_id != 0 LEFT JOIN `authorization_role` AS `detail_role` ON user_role.parent_id = detail_role.role_id WHERE (`admin_user.user_id` = '1')
```

**Comment by phoenix128** [comment]
Fixed by https://github.com/magespecialist/magespecialist_TwoFactorAuth/commit/a1054d3e53301aef82ccc43146d152aaed4bf425
