### ISSUE TITLE
Couldn't configure 2FA providers without forcing them

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#5]
### Preconditions:
**'2FA'** is globally enabled but **Force providers** chechbox is left to **Use system value**

### Steps to reproduce:
1. Log in to Magento backend
2. Navigate to Stores > Settings > Configuration > Security Suite > 2FA > 
3. Switch **Enable this provider** to **Yes** in the  **Google Authenticator** section
4. Switch **Enable this provider** to **Yes** In the **U2F Devices (Yubikey and others)** section
5. In the **Duo Security** section
- Switch **Enable this provider** to **Yes**
- Provide a valid Integration Key
- Provide a valid Secret Key
- Provide a valid API hostname
6. In the **Authy** section
- Provide a valid API key
- Switch **Enable this provider** to **Yes**
7. Save configuration and flush Magento configuration cache

### Expected result:
:white_check_mark: The Google Authenticator provider should be enabled and configured
:white_check_mark: The U2F provider should be enabled and configured
:white_check_mark: The Duo Security provider should be enabled and configured
:white_check_mark: The Authy provider should be enabled and configured

### Actual result:
:x: Nothing is configured until providers are not forced

**Comment by phoenix128** [comment]
I think there is a misunderstaing in this feature.
If you do not force providers, you allow them to be **enabled indidually** in the user's configuration page.
If no provider is set in the user's profile then no provider will be used or enrolled.

![senzanome](https://user-images.githubusercontent.com/10189093/35508994-cd82287e-04f2-11e8-905b-576e071184b4.png)

**Comment by TomashKhamlai** [comment]
Fixed because #4 was fixed
