### ISSUE TITLE
No way to switch to another account if you have no access to authentication method of selected one

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#8]
**Preconditions:**
2 admins
Google Authentication is allowed

**Steps to reproduce:**
Go to the second admin and enable Google Auth in 2FA section of the current user.
You will be redirected to scan a QR-code
Do not scan QR.
Try to sign in as a first admin.

**Expected result:**
There should be 'reset' or 'go back' button to start from the beginning or there should be 2-3 minutes timeout for scanning until the user will be asked to enter the username and password.

**Actual result:**
It is possible to reset if you have access to the server
It is possible to clean cookies if you know how cookies works
You are forced to wait until the end of session

**Comment by phoenix128** [comment]
I agree, but this conflicts with the possibility from the admin point of view of forcing others to use 2FA.
Do you think a logout button could work in your specific example?

**Comment by vkublytskyi** [comment]
@phoenix128, seems this functionality is broken on the latest code.

I have enabled 2FA with Google Authenticator and U2F Devices (non is forced). Go to System > All Users > any user > 2FA tab. Mark checkbox for  Google Authenticator as checked and save. After page reload checkbox is not checked.

**Comment by TomashKhamlai** [comment]
I have the same user experience as @vkublytskyi today.
Yesterday, there were no problems with this, because I was using the outdated code.

**Comment by phoenix128** [comment]
You have this fixed in https://github.com/magento/magespecialist_TwoFactorAuth/pull/1/commits/d2cdc7244f07cb658f9e962e8119f5cb628bde92 .
