### ISSUE TITLE
Could you please remove the logo and description from ./etc/adminhtml/system.xml?

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#9]
All the functionality is going to be documented in Magento Documentation with screenshots in very descriptive manner. Someone from Magento team will create it. You can propose the changes to the documentation later.

**Comment by phoenix128** [comment]
Fixed in 904a78ffacf1729b528ba4ecc543a935afcaadde

**Comment by TomashKhamlai** [comment]
Thank you!
